<?php
/**
 * English Language File
 */
$lang = [
// Login Page
'bank_name' => 'Mercantil Bank',
'bank_logo_alt' => 'Mercantil Bank Logo',
'login' => 'Login',
'username_placeholder' => 'Username',
'password_placeholder' => 'Password',
'login_button_text' => 'Sign In',
'forgot_password' => 'Forgot password?',
'fill_all_fields' => 'Please fill in all fields',
'spanish' => 'Spanish',
'english' => 'English',
'portuguese' => 'Portuguese',
'version' => 'Version',





// Error Page
'error_title' => 'Error - Mercantil Bank',
'error_heading' => 'Oops! An error has occurred',
'error_message_1' => 'Sorry, the page you are looking for does not exist or is not available at this time.',
'error_message_2' => 'Please verify the URL or return to the home page.',
'return_home' => 'Return to home',





// MAIN.PHP Layout Elements
'app_name' => 'Mercantil Bank',
'welcome' => 'Welcome',
'language' => 'Language',
'language_es' => 'Spanish',
'language_en' => 'English',
'profile' => 'My Profile',
'settings' => 'Settings',
'logout' => 'Logout',
'financial_panel' => 'Financial Panel',
'home' => 'Home',
'cards' => 'Cards',
'clients' => 'Clients',
'accounts' => 'Accounts',
'transactions' => 'Transactions',
'reports' => 'Reports',
'branches' => 'Branches',
'atm' => 'ATM',
'version' => 'v2.5.3',




    // BIENVENIDA.PHP
    'welcome_message_title' => 'Integrated Banking Management System',
    'welcome_message' => 'Welcome to Mercantil Bank System. This platform allows you to efficiently manage all banking operations, including customer management, accounts, transactions, and reports.',
    'quick_access' => 'Quick Access',
    'home' => 'Home',
    'total_balance_bolivianos' => 'Total Balance (Bs.)',
    'total_balance_dollars' => 'Total Balance ($)',
    'view_all_transactions' => 'View all transactions',
    'last_update' => 'Last update',
    'about' => 'About',
    'about_description' => 'Banking system developed for Mercantil Bank that allows the comprehensive management of clients, accounts and financial transactions.',
    'system_information' => 'System Information',
    'version' => 'Version',
    'developer' => 'Developer',
    'features' => 'Features',
    'client_management' => 'Client management',
    'account_management' => 'Account management',
    'transaction_processing' => 'Transaction processing',
    'reporting_system' => 'Reporting system',
    'multilanguage_support' => 'Multilanguage support',
    'pwa_compatibility' => 'PWA compatibility',
    'back_to_home' => 'Back to home',



    // Values
    'our_values' => 'OUR VALUES',
    'values_description' => 'The pillars that guide our service mission',
    'leadership' => 'Leadership',
    'leadership_desc' => '"To be recognized as the best financial bank."',
    'customer_service' => 'Customer Service',
    'customer_service_desc' => '"Meet our customers\' expectations"',
    'reliability' => 'Reliability',
    'reliability_desc' => '"Efficiently fulfill our commitments."',
    'integrity' => 'Integrity',
    'integrity_desc' => '"Act with honesty, loyalty and professional ethics"',
    'professionalism' => 'Professionalism',
    'professionalism_desc' => '"Perform outstanding management"',

    // Commitment
    'our_commitment' => 'OUR COMMITMENT TO YOU',
    'commitment_subtitle' => 'We accompany you in every step of your financial journey',
    'support_24_7' => '24/7 Support',
    'maximum_security' => 'Maximum security',
    'expert_advice' => 'Expert advice',
    'mobile_banking' => 'Mobile banking',
    'personalized_attention' => 'Personalized attention',
    'guaranteed_security' => 'Guaranteed security',
    'sustainable_growth' => 'Sustainable growth',

    // Footer
    'terms_conditions' => 'Terms and Conditions',
    'privacy_policy' => 'Privacy Policy',
    'version_info' => 'Version: 1.0.0',







// SECCION TARJETAS

    // LISTAR/TARJETAS.PHP
    'card_list' => 'Card List',
    'new_card' => 'New Card',
    'no_cards' => 'No cards registered in the system.',
    'card_number' => 'Card Number',
    'card_type' => 'Card Type',
    'expiration_date' => 'Expiration Date',
    'account_number' => 'Account Number',
    'client_name' => 'Client Name',
    'status' => 'Status',
    'actions' => 'Actions',
    'debit' => 'Debit',
    'credit' => 'Credit',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'view' => 'View',
    'edit' => 'Edit',
    'deactivate' => 'Deactivate',
    'activate' => 'Activate',
    'delete' => 'Delete',
    'confirm_deactivate_card' => 'Are you sure you want to deactivate this card?',
    'confirm_activate_card' => 'Are you sure you want to activate this card?',
    'confirm_delete_card' => 'Are you sure you want to delete this card? This action cannot be undone.',



    // Card Details View
'card_details' => 'Card Details',
'valid_until' => 'VALID UNTIL',
'sensitive_data_message' => 'Sensitive data such as card number, CVV, and PIN are masked for security. Click on the eye icons to reveal the information.',
'card_information' => 'Card Information',
'account_information' => 'Account Information',
'associated_account' => 'Associated Account',
'checking_account' => 'Checking Account',
'view_account' => 'View Account',
'transaction_history' => 'Transaction History',
'client_information' => 'Client Information',
'personal_information' => 'Personal Information',
'contact_information' => 'Contact Information',
'branch' => 'Branch',
'view_full_profile' => 'View Full Profile',
'view_history' => 'View History',
'back' => 'Back',
'card_number' => 'Card Number:',
'tipo_de_cuenta' => 'Account Type:',
'moneda' => 'Currency:',
'saldo' => 'Balance:',
'fecha_de_apertura' => 'Opening Date:',
'nombre' => 'Name:',
'apellido_paterno' => 'Paternal Last Name:',
'apellido_materno' => 'Maternal Last Name:',
'numero_de_identificacion' => 'ID Number:',
'fecha_de_nacimiento' => 'Birth Date:',
'direccion' => 'Address:',
'telefono' => 'Phone:',
'correo_electronico' => 'Email:',
'branch' => 'Branch:',
'view_account' => 'View Account',
'transaction_history' => 'Transaction History',
'view_full_profile' => 'View Full Profile',
'view_history' => 'View History',



// Vista Editar Tarjeta
'edit_card_data' => 'Edit Card Data',
'editing_card' => 'Editing Card',
'bank_short' => 'BANK M',
'bank_full_name' => 'MERCANTIL SANTA CRUZ',
'authorized_client' => 'AUTHORIZED CLIENT',
'valid_until' => 'VALID UNTIL',
'debit_card' => 'Debit Card',
'security_hash' => 'Security hash',
'verify' => 'Verify',
'limits' => 'Limits',
'block' => 'Block',
'issue_date' => 'Issue date',
'head_office' => 'Head Office',
'international_use' => 'International use',
'enabled' => 'Enabled',
'security' => 'Security',
'pci_dss_standard' => 'PCI DSS Standard',
'select_account' => 'Select an account',
'please_select_account' => 'Please select an associated account.',
'account_card_association_info' => 'This account will be associated with the card for transactions',
'select_option' => 'Select an option',
'please_select_card_type' => 'Please select the card type.',
'please_enter_valid_card_number' => 'Please enter a valid card number.',
'card_number_format_help' => 'Enter the 16 digits of the card separated in groups of 4',
'cvv_tooltip' => '3-digit security code located on the back of the card',
'secure_field' => 'Secure field',
'cvv_validation' => 'The CVV must have 3 digits.',
'cvv_help' => '3-digit security code',
'expiration_date_validation' => 'Please enter a valid date (MM/YY).',
'expiration_date_format' => 'Format: MM/YY (example: 12/25)',
'pin_tooltip' => '4-digit secret code for use at ATMs and merchants',
'show_hide_pin' => 'Show/Hide PIN',
'pin_validation' => 'The PIN must have 4 digits.',
'pin_help' => '4-digit numeric code',
'security_measures' => 'Security Measures',
'last_modification' => 'Last Modification',
'security_notice' => 'Security Notice',
'security_notice_text' => 'Any change to the card information will be recorded and may require additional verification. PIN changes or card blocking will be applied immediately.',
'save_changes' => 'Save Changes',
'cancel' => 'Cancel',
'block_card' => 'Block Card',



// New Card
'new_card' => 'New Card',
'account' => 'Account',
'type' => 'Type',
'number' => 'Number',
'select_card_type' => 'Select card type',
'card_number_required' => 'Card number is required',
'auto_generated_number' => 'The number is automatically generated',
'cvv_required' => 'CVV is required',
'expiration_date_required' => 'Expiration date is required',
'expiration_date_format_short' => 'Format: MM/YY',
'pin_required' => 'PIN is required',
'pin_digits_info' => 'Must contain 4 numeric digits',
'select_status' => 'Select a status',
'additional_information' => 'Additional Information',
'credit_limit' => 'Credit Limit',
'credit_limit_info' => 'Maximum limit for credit cards',
'notes' => 'Notes',
'additional_card_info' => 'Additional information about the card (optional)',
'save' => 'Save',





//SECCION DE CLIENTES

// Client List
'client_list' => 'Client List',
'new_client' => 'New Client',
'no_clients_registered' => 'There are no clients registered in the system.',
'identity_card' => 'Identity Card',
'name' => 'Name',
'paternal_surname' => 'Paternal Surname',
'maternal_surname' => 'Maternal Surname',
'phone' => 'Phone',
'office' => 'Office',
'actions' => 'Actions',
'view_details' => 'View details',
'edit' => 'Edit',
'delete' => 'Delete',




// Create Client
'new_client' => 'New Client',
'name' => 'Name',
'name_required' => 'The name is required',
'paternal_last_name' => 'Paternal Last Name',
'paternal_last_name_required' => 'The paternal last name is required',
'maternal_last_name' => 'Maternal Last Name',
'address' => 'Address',
'phone' => 'Phone',
'email' => 'Email',
'valid_email_required' => 'Enter a valid email',
'birth_date' => 'Birth Date',
'id_number' => 'Identity Card',
'id_number_required' => 'The identity card is required',
'branch' => 'Branch Office',
'branch_required' => 'The branch office is required',
'save' => 'Save',
'cancel' => 'Cancel',
'select_option' => 'Select an option',


// View Client
'client_details' => 'Client Details',
'view_mode' => 'View Mode',
'id_short' => 'ID',
'client_id' => 'Client ID',
'identity_document' => 'ID / Document',
'registration_date' => 'Registration Date',
'client_type' => 'Client Type',
'personal' => 'Personal',
'business' => 'Business',
'bank_accounts' => 'Bank Accounts',
'new_account' => 'New Account',
'no_accounts' => 'There are no accounts associated with this client.',
'create_account' => 'Create Account',
'account_number' => 'Account No.',
'currency' => 'Currency',
'balance' => 'Balance',
'opening_date' => 'Opening Date',
'savings' => 'Savings',
'checking' => 'Checking',
'bolivianos' => 'Bolivianos (Bs)',
'dollars' => 'Dollars ($)',
'view' => 'View',
'deposit' => 'Deposit',
'withdraw' => 'Withdraw',
'recent_transactions' => 'Recent Transactions',
'view_all' => 'View all',
'no_transactions' => 'There are no transactions registered for this client.',
'date' => 'Date',
'time' => 'Time',
'account' => 'Account',
'description' => 'Description',
'amount' => 'Amount',
'withdrawal' => 'Withdrawal',
'received_transfer' => 'Received Transfer',
'sent_transfer' => 'Sent Transfer',
'other' => 'Other',
'deactivate' => 'Deactivate',
'activate' => 'Activate',
'back_to_list' => 'Back to List',
'confirm_deactivate_client' => 'Are you sure you want to deactivate this client?',
'confirm_activate_client' => 'Are you sure you want to activate this client?',




//SECCION DE CUENTAS

// View Account
'account_details' => 'Account Details',
'view_mode' => 'View Mode',
'deposit' => 'Deposit',
'withdraw' => 'Withdraw',
'transfer' => 'Transfer',
'statement' => 'Statement',
'account_information' => 'Account Information',
'account_number' => 'Account Number',
'account_type' => 'Account Type',
'savings_account' => 'Savings Account',
'checking_account' => 'Checking Account',
'currency' => 'Currency',
'current_balance' => 'Current Balance',
'opening_date' => 'Opening Date',
'status' => 'Status',
'active' => 'Active',
'inactive' => 'Inactive',
'client_information' => 'Client Information',
'surnames' => 'Surnames',
'identity_document' => 'ID / Document',
'view_client' => 'View Client',
'view_client_details' => 'View client details',
'recent_transactions' => 'Recent Transactions',
'view_full_statement' => 'View Full Statement',
'no_transactions_account' => 'There are no transactions registered for this account.',
'date' => 'Date',
'time' => 'Time',
'type' => 'Type',
'description' => 'Description',
'amount' => 'Amount',
'resulting_balance' => 'Resulting Balance',
'withdrawal' => 'Withdrawal',
'received_transfer' => 'Received Transfer',
'sent_transfer' => 'Sent Transfer',
'other' => 'Other',
'view_all_transactions' => 'View all transactions',
'edit' => 'Edit',
'close_account' => 'Close Account',
'reactivate_account' => 'Reactivate Account',
'back_to_list' => 'Back to List',
'confirm_close_account' => 'Are you sure you want to close this account?',
'confirm_reactivate_account' => 'Are you sure you want to reactivate this account?',


// Account List
'account_list' => 'Account List',
'new_account' => 'New Account',
'no_accounts_registered' => 'There are no accounts registered in the system.',
'account_number' => 'Account Number',
'client' => 'Client',
'account_type' => 'Account Type',
'currency' => 'Currency',
'balance' => 'Balance',
'opening_date' => 'Opening Date',
'status' => 'Status',
'savings' => 'Savings',
'checking' => 'Checking',
'bolivianos_short' => 'Bolivianos',
'dollars_short' => 'Dollars',
'active' => 'Active',
'inactive' => 'Inactive',
'view_details' => 'View details',
'edit' => 'Edit',
'deposit' => 'Deposit',
'withdraw' => 'Withdraw',




// Create Account
'new_account' => 'New Account',
'client' => 'Client',
'select_client' => 'Select a client',
'client_required' => 'The client is required',
'account_type' => 'Account Type',
'account_type_required' => 'The account type is required',
'savings_account' => 'Savings Account',
'checking_account' => 'Checking Account',
'currency' => 'Currency',
'currency_required' => 'The currency is required',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dollars',
'initial_balance' => 'Initial Balance',
'initial_balance_help' => 'Balance with which the account will be started',
'save' => 'Save',
'cancel' => 'Cancel',
'select_option' => 'Select an option',


// Edit Account
'edit_account' => 'Edit Account',
'editing_mode' => 'Editing Mode',
'account_number' => 'Account Number',
'client' => 'Client',
'currency' => 'Currency',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dollars',
'balance' => 'Balance',
'opening_date' => 'Opening Date',
'account_type' => 'Account Type',
'savings_account' => 'Savings Account',
'checking_account' => 'Checking Account',
'account_type_required' => 'The account type is required',
'status' => 'Status',
'active' => 'Active',
'inactive' => 'Inactive',
'status_required' => 'The status is required',
'save' => 'Save',
'cancel' => 'Cancel',



//SECCION DE TRANSACCIONES

// Transaction List
'transaction_list' => 'Transaction List',
'search_transactions' => 'Search Transactions',
'withdrawal' => 'Withdrawal',
'deposit' => 'Deposit',
'print' => 'Print',
'no_transactions' => 'There are no transactions registered in the system.',
'date' => 'Date',
'time' => 'Time',
'transaction_type' => 'Transaction Type',
'account_number' => 'Account Number',
'client' => 'Client',
'description' => 'Description',
'amount' => 'Amount',
'actions' => 'Actions',
'transfer_received' => 'Transfer Received',
'transfer_sent' => 'Transfer Sent',
'other' => 'Other',
'view' => 'View',
'receipt' => 'Receipt',




// View Transaction
'transaction_details' => 'Transaction Details',
'view_mode' => 'View Mode',
'withdrawal' => 'Withdrawal',
'deposit' => 'Deposit',
'transfer_received' => 'Transfer Received',
'transfer_sent' => 'Transfer Sent',
'other_operation' => 'Other Operation',
'transaction_id_with_number' => 'Transaction #%s',
'date_time_format' => '%s at %s',
'transaction_information' => 'Transaction Information',
'transaction_id' => 'Transaction ID',
'transaction_type' => 'Transaction Type',
'date' => 'Date',
'time' => 'Time',
'amount' => 'Amount',
'resulting_balance' => 'Resulting Balance',
'description' => 'Description',
'source_account' => 'Source Account',
'destination_account' => 'Destination Account',
'account_information' => 'Account Information',
'account_number' => 'Account Number',
'account_type' => 'Account Type',
'savings' => 'Savings',
'checking' => 'Checking',
'currency' => 'Currency',
'bolivianos' => 'Bolivianos (Bs)',
'dollars' => 'Dollars ($)',
'client_information' => 'Client Information',
'full_name' => 'Full Name',
'identity_document' => 'ID / Document',
'print_receipt' => 'Print Receipt',
'back_to_list' => 'Back to List',



// Transaction Receipt
'transaction_receipt' => 'Transaction Receipt',
'bank_name' => 'Mercantil Bank',
'receipt' => 'RECEIPT',
'transaction_receipt_title' => 'TRANSACTION RECEIPT',
'id' => 'ID',
'withdrawal_receipt' => 'WITHDRAWAL RECEIPT',
'deposit_receipt' => 'DEPOSIT RECEIPT',
'transfer_received_receipt' => 'TRANSFER RECEIVED RECEIPT',
'transfer_sent_receipt' => 'TRANSFER SENT RECEIPT',
'receipt_security_message' => 'This document is an official receipt from Mercantil Bank. Please verify the information before proceeding.',
'branch' => 'Branch',
'head_office' => 'Head Office',
'attended_by' => 'Attended by',
'online_transaction' => 'Online transaction',
'verification_qr_code' => 'Verification QR code',
'scan_qr_code' => 'Scan the QR code to verify authenticity',
'transaction_reference' => 'Reference',
'receipt_thank_you' => 'Thank you for trusting Mercantil Bank!',
'receipt_valid_without_signature' => 'This receipt is valid without signature or stamp.',
'receipt_contact_info' => 'For any inquiries, please contact 0800-BANCO (22626)',
'generated_on' => 'Generated on',
'print' => 'Print',
'back' => 'Back',
'download_pdf' => 'Download PDF',
'send_by_email' => 'Send by Email',
'report_issue' => 'Report Issue',
'verification_seal' => 'Verification seal',
'pdf_download_started' => 'PDF download started...',
'enter_email' => 'Please enter your email address:',
'email_sent' => 'Receipt sent to email.',
'describe_issue' => 'Please describe the issue:',
'issue_reported' => 'Issue reported. Thank you for your feedback.',



// Transaction Search
'transaction_search' => 'Transaction Search',
'account' => 'Account',
'all_accounts' => 'All accounts',
'all_types' => 'All types',
'start_date' => 'Start Date',
'end_date' => 'End Date',
'search' => 'Search',
'search_results' => 'Search Results',
'type' => 'Type',
'atm_withdrawal' => 'ATM withdrawal',
'counter_deposit' => 'Counter deposit',
'view' => 'View',
'receipt' => 'Receipt',
'advanced_options' => 'Advanced options',
'hide_advanced' => 'Hide advanced options',
'min_amount' => 'Minimum amount',
'max_amount' => 'Maximum amount',
'description_contains' => 'Description contains',
'previous_page' => 'Previous page',
'next_page' => 'Next page',
'page' => 'Page',
'of' => 'of',
'print' => 'Print',
'back' => 'Back',
'export' => 'Export',
'export_as' => 'Export as',
'excel' => 'Excel',
'pdf' => 'PDF',
'csv' => 'CSV',
'exporting' => 'Exporting',





// Funds Withdrawal
'withdrawal' => 'Funds Withdrawal',
'bank_name' => 'Mercantil Bank',
'enter_account_number_to_withdraw' => 'Enter the account number from which you want to make the withdrawal.',
'account_number' => 'Account Number',
'enter_account_number' => 'Enter account number',
'search' => 'Search',
'cancel' => 'Cancel',
'account_information' => 'Account Information',
'account_type' => 'Account Type',
'savings_account' => 'Savings Account',
'checking_account' => 'Checking Account',
'currency' => 'Currency',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dollars',
'available_balance' => 'Available Balance',
'client_information' => 'Client Information',
'name' => 'Name',
'last_name' => 'Last Name',
'id_number' => 'ID Number',
'amount' => 'Amount',
'amount_required' => 'Please enter a valid amount.',
'max_amount' => 'Maximum amount',
'description' => 'Description',
'cash_withdrawal' => 'Cash withdrawal',
'withdraw' => 'Withdraw',
'where_find_account_number' => 'Where to find my account number?',
'account_number_locations' => 'Your number appears on your passbook, debit card or mobile app',
'verify_available_balance' => 'Verify available balance',
'ensure_sufficient_funds' => 'Make sure you have sufficient funds before withdrawing',
'account_authorization' => 'Account authorization',
'account_authorization_info' => 'You can only withdraw from accounts where you are the holder or have authorization',
'withdrawal_limits' => 'Withdrawal limits',
'max_amount_depends' => 'The maximum amount depends on the account type and available balance',
'example_accounts' => 'Example Accounts',
'savings' => 'Savings',
'personal_account' => 'Personal Account',
'checking' => 'Checking',
'business_account' => 'Business Account',
'payroll' => 'Payroll',
'salary_account' => 'Salary Account',




// Funds Deposit
'deposit_funds' => 'Deposit Funds',
'bank_name' => 'Mercantil Bank',
'enter_account_number_to_deposit' => 'Enter the account number in which you want to make the deposit.',
'account_number' => 'Account Number',
'enter_account_number' => 'Enter account number',
'search' => 'Search',
'cancel' => 'Cancel',
'account_information' => 'Account Information',
'account_type' => 'Account Type',
'savings_account' => 'Savings Account',
'checking_account' => 'Checking Account',
'currency' => 'Currency',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dollars',
'client_information' => 'Client Information',
'name' => 'Name',
'last_name' => 'Last Name',
'id_number' => 'ID Number',
'amount' => 'Amount',
'amount_required' => 'Please enter a valid amount.',
'description' => 'Description',
'cash_deposit' => 'Cash deposit',
'deposit' => 'Deposit',
'where_find_account_number' => 'Where to find the account number?',
'account_number_locations' => 'The number appears on the passbook, debit card or mobile app',
'deposit_types' => 'Deposit types',
'deposit_types_info' => 'You can make deposits in cash, check or transfer',
'deposit_limits' => 'Deposit limits',
'deposit_limits_info' => 'Check the limits according to the account type and channel used',
'crediting_time' => 'Crediting time',
'crediting_time_info' => 'Cash deposits are credited immediately',
'example_accounts' => 'Example Accounts',
'savings' => 'Savings',
'personal_account' => 'Personal Account',
'checking' => 'Checking',
'business_account' => 'Business Account',
'payroll' => 'Payroll',
'salary_account' => 'Salary Account',



// Reports
'reports' => 'Reports',
'print' => 'Print',
'note' => 'Note',
'reports_note' => 'Reports are generated in real time with updated system data.',
'transactions_stats_reports' => 'Transaction and Statistics Reports',
'report_name' => 'Report Name',
'description' => 'Description',
'actions' => 'Actions',
'transactions_by_date' => 'Transactions by Date',
'transactions_by_date_desc' => 'Detailed report of transactions made within a selected date range.',
'view_report' => 'View Report',
'transactions_by_client' => 'Transactions by Client',
'transactions_by_client_desc' => 'Transaction history grouped by client for detailed activity analysis.',
'atm_statistics' => 'ATM Statistics',
'atm_statistics_desc' => 'Analysis of ATM usage, transactions, and availability.',
'balances_activity_reports' => 'Balance and Activity Reports',
'balances_by_branch' => 'Balances by Branch',
'balances_by_branch_desc' => 'Consolidated balance report by branch and account type.',
'account_activity' => 'Account Activity',
'account_activity_desc' => 'Detailed activity history for all accounts in a selected period.',
'executive_summary' => 'Executive Summary',
'executive_summary_desc' => 'General summary of statistics and key indicators for management.',
'performance_audit_reports' => 'Performance and Audit Reports',
'product_performance' => 'Product Performance',
'product_performance_desc' => 'Performance analysis for each financial product offered by the bank.',
'system_audit' => 'System Audit',
'system_audit_desc' => 'Record of all operations and changes made in the system by user.',
'service_metrics' => 'Service Metrics',
'service_metrics_desc' => 'Service quality and customer satisfaction statistics across all branches.',






// Branch List
'branch_list' => 'Branch List',
'new_branch' => 'New Branch',
'no_branches_found' => 'No branches registered in the system.',
'name' => 'Name',
'address' => 'Address',
'city' => 'City',
'phone' => 'Phone',
'type' => 'Type',
'status' => 'Status',
'actions' => 'Actions',
'central' => 'Central',
'branch' => 'Branch',
'active' => 'Active',
'inactive' => 'Inactive',
'view' => 'View',
'edit' => 'Edit',
'deactivate' => 'Deactivate',
'activate' => 'Activate',
'delete' => 'Delete',
'confirm_deactivate_branch' => 'Are you sure you want to deactivate this branch?',
'confirm_activate_branch' => 'Are you sure you want to activate this branch?',
'confirm_delete_branch' => 'Are you sure you want to delete this branch? This action cannot be undone.',

// Edit Branch
'edit_office' => 'Edit Branch',
'editing_mode' => 'Editing Mode',
'name_required' => 'Name is required',
'address_required' => 'Address is required',
'city_required' => 'City is required',
'state' => 'State',
'state_required' => 'State is required',
'country' => 'Country',
'country_required' => 'Country is required',
'office_hours' => 'Office Hours',
'office_hours_placeholder' => 'Ex: Monday to Friday 8:00 AM - 4:00 PM',
'manager' => 'Branch Manager',
'opening_date' => 'Opening Date',
'branch_type' => 'Branch Type',
'save' => 'Save',
'cancel' => 'Cancel',




// CREATE BRANCH
'new_branch' => 'New Branch',
'name_required' => 'Name is required',
'address_required' => 'Address is required',
'office_hours_placeholder' => 'Ex: Monday to Friday: 8:30 AM - 4:30 PM, Saturday: 8:30 AM - 12:30 PM',



// View Branch
'branch_details' => 'Branch Details',
'view_mode' => 'View Mode',
'id' => 'ID',
'central' => 'Main Office',
'branch' => 'Branch',
'active' => 'Active',
'inactive' => 'Inactive',
'general_information' => 'General Information',
'name' => 'Name',
'address' => 'Address',
'city' => 'City',
'state' => 'State',
'country' => 'Country',
'phone' => 'Phone',
'office_hours' => 'Office Hours',
'manager' => 'Manager',
'opening_date' => 'Opening Date',
'branch_type' => 'Branch Type',
'status' => 'Status',
'employees' => 'Employees',
'new_employee' => 'New Employee',
'no_employees' => 'There are no employees assigned to this branch.',
'add_employee' => 'Add Employee',
'position' => 'Position',
'email' => 'Email',
'actions' => 'Actions',
'view' => 'View',
'edit' => 'Edit',
'back_to_list' => 'Back to List',
'deactivate' => 'Deactivate',
'activate' => 'Activate',
'confirm_deactivate' => 'Are you sure you want to deactivate this branch?',
'confirm_activate' => 'Are you sure you want to activate this branch?',


// ATM Transaction List
'atm_transaction_list' => 'ATM Transaction List',
'search_atm_transactions' => 'Search ATM Transactions',
'withdrawal' => 'Withdrawal',
'deposit' => 'Deposit',
'no_transactions' => 'There are no transactions registered in the system.',
'date' => 'Date',
'time' => 'Time',
'transaction_type' => 'Type',
'description' => 'Description',
'account_number' => 'Account No.',
'amount' => 'Amount',
'resulting_balance' => 'Resulting Balance',
'client' => 'Client',
'atm' => 'ATM',
'actions' => 'Actions',
'inquiry' => 'Inquiry',
'other' => 'Other',
'view' => 'View',
'receipt' => 'Receipt',
'print' => 'Print',

];
?>