<?php
/**
 * Spanish Language File
 */
$lang = [

// Página de Login
'bank_name' => 'Banco Mercantil',
'bank_logo_alt' => 'Logo de Banco Mercantil',
'login' => 'Iniciar Sesión',
'username_placeholder' => 'Nombre de usuario',
'password_placeholder' => 'Contraseña',
'login_button_text' => 'Iniciar Sesión',
'forgot_password' => '¿Olvidó su contraseña?',
'fill_all_fields' => 'Por favor complete todos los campos',
'spanish' => 'Español',
'english' => 'English',
'portuguese' => 'Português',
'version' => 'Versión',

// Página de Error
'error_title' => 'Error - Banco Mercantil',
'error_heading' => '¡Oops! Ha ocurrido un error',
'error_message_1' => 'Lo sentimos, la página que estás buscando no existe o no está disponible en este momento.',
'error_message_2' => 'Por favor, verifica la URL o regresa a la página de inicio.',
'return_home' => 'Volver al inicio',


// MAIN.PHP Layout Elements
'app_name' => 'Banco Mercantil',
'welcome' => 'Bienvenido',
'language' => 'Idioma',
'language_es' => 'Español',
'language_en' => 'English',
'profile' => 'Mi Perfil',
'settings' => 'Configuración',
'logout' => 'Cerrar Sesión',
'financial_panel' => 'Panel Financiero',
'home' => 'Inicio',
'cards' => 'Tarjetas',
'clients' => 'Clientes',
'accounts' => 'Cuentas',
'transactions' => 'Transacciones',
'reports' => 'Reportes',
'branches' => 'Oficinas',
'atm' => 'Cajero Automático',
'version' => 'v2.5.3',



//SECCION BIENVENIDA
// Tarjetas
'card_list' => 'Lista de Tarjetas',
'new_card' => 'Nueva Tarjeta',
'no_cards' => 'No hay tarjetas registradas en el sistema.',
'card_number' => 'Número de Tarjeta',
'card_type' => 'Tipo de Tarjeta',
'expiration_date' => 'Fecha de Expiración',
'account_number' => 'Número de Cuenta',
'client_name' => 'Nombre del Cliente',
'status' => 'Estado',
'actions' => 'Acciones',
'debit' => 'Débito',
'credit' => 'Crédito',
'active' => 'Activa',
'inactive' => 'Inactiva',
'view' => 'Ver',
'edit' => 'Editar',
'deactivate' => 'Desactivar',
'activate' => 'Activar',
'delete' => 'Eliminar',
'confirm_deactivate_card' => '¿Está seguro que desea desactivar esta tarjeta?',
'confirm_activate_card' => '¿Está seguro que desea activar esta tarjeta?',
'confirm_delete_card' => '¿Está seguro que desea eliminar esta tarjeta? Esta acción no se puede deshacer.',

// Valores
'our_values' => 'NUESTROS VALORES',
'values_description' => 'Los pilares que guían nuestra misión de servicio',
'leadership' => 'Liderazgo',
'leadership_desc' => '"Ser reconocidos como el mejor banco financiero."',
'customer_service' => 'Servicio al cliente',
'customer_service_desc' => '"Satisfacer las expectativas de nuestros clientes"',
'reliability' => 'Confiabilidad',
'reliability_desc' => '"Cumplir eficientemente con los compromisos pactados."',
'integrity' => 'Integridad',
'integrity_desc' => '"Actuar con honestidad, lealtad y ética profesional"',
'professionalism' => 'Profesionalismo',
'professionalism_desc' => '"Desempeñar una gestión sobresaliente"',

// Compromiso
'our_commitment' => 'NUESTRO COMPROMISO CONTIGO',
'commitment_subtitle' => 'Te acompañamos en cada paso de tu camino financiero',
'support_24_7' => 'Soporte 24/7',
'maximum_security' => 'Máxima seguridad',
'expert_advice' => 'Asesoría experta',
'mobile_banking' => 'Banca móvil',
'personalized_attention' => 'Atención personalizada',
'guaranteed_security' => 'Seguridad garantizada',
'sustainable_growth' => 'Crecimiento sostenible',

// Footer
'terms_conditions' => 'Términos y Condiciones',
'privacy_policy' => 'Política de Privacidad',
'version_info' => 'Versión: 1.0.0',    








// SECCION TARJETAS

// LISTAR/TARJETAS.PHP
'card_list' => 'Lista de Tarjetas',
'new_card' => 'Nueva Tarjeta',
'no_cards' => 'No hay tarjetas registradas en el sistema.',
'card_number' => 'Número de Tarjeta',
'card_type' => 'Tipo de Tarjeta',
'expiration_date' => 'Fecha de Expiración',
'account_number' => 'Número de Cuenta',
'client_name' => 'Nombre del Cliente',
'status' => 'Estado',
'actions' => 'Acciones',
'debit' => 'Débito',
'credit' => 'Crédito',
'active' => 'Activa',
'inactive' => 'Inactiva',
'view' => 'Ver',
'edit' => 'Editar',
'deactivate' => 'Desactivar',
'activate' => 'Activar',
'delete' => 'Eliminar',
'confirm_deactivate_card' => '¿Está seguro que desea desactivar esta tarjeta?',
'confirm_activate_card' => '¿Está seguro que desea activar esta tarjeta?',
'confirm_delete_card' => '¿Está seguro que desea eliminar esta tarjeta? Esta acción no se puede deshacer.',


// Vista de detalles de tarjeta
'card_details' => 'Detalles de Tarjeta',
'valid_until' => 'VÁLIDA HASTA',
'sensitive_data_message' => 'Los datos sensibles como el número de tarjeta, CVV y PIN están enmascarados por seguridad. Haga clic en los iconos de ojo para revelar la información.',
'card_information' => 'Información de Tarjeta',
'account_information' => 'Información de Cuenta',
'associated_account' => 'Cuenta Asociada',
'checking_account' => 'Cuenta Corriente',
'view_account' => 'Ver Cuenta',
'transaction_history' => 'Historial de Transacciones',
'client_information' => 'Información del Cliente',
'personal_information' => 'Datos Personales',
'contact_information' => 'Información de Contacto',
'branch' => 'Sucursal',
'view_full_profile' => 'Ver Perfil Completo',
'view_history' => 'Ver Historial',
'back' => 'Volver',
'card_number' => 'Card Number:',
'tipo_de_cuenta' => 'Tipo de Cuenta:',
'moneda' => 'Moneda:',
'saldo' => 'Saldo:',
'fecha_de_apertura' => 'Fecha de Apertura:',
'nombre' => 'Nombre:',
'apellido_paterno' => 'Apellido Paterno:',
'apellido_materno' => 'Apellido Materno:',
'numero_de_identificacion' => 'Número de Identificación:',
'fecha_de_nacimiento' => 'Fecha de Nacimiento:',
'direccion' => 'Dirección:',
'telefono' => 'Teléfono:',
'correo_electronico' => 'Correo Electrónico:',
'branch' => 'Branch:',
'view_account' => 'View Account',
'transaction_history' => 'Transaction History',
'view_full_profile' => 'View Full Profile',
'view_history' => 'View History',



// Vista Editar Tarjeta
'edit_card_data' => 'Editar Datos de la Tarjeta',
'editing_card' => 'Editando Tarjeta',
'bank_short' => 'BANCO M',
'bank_full_name' => 'MERCANTIL SANTA CRUZ',
'authorized_client' => 'CLIENTE AUTORIZADO',
'valid_until' => 'VÁLIDO HASTA',
'debit_card' => 'Tarjeta de Débito',
'security_hash' => 'Hash de seguridad',
'verify' => 'Verificar',
'limits' => 'Límites',
'block' => 'Bloquear',
'issue_date' => 'Fecha de emisión',
'head_office' => 'Casa Matriz',
'international_use' => 'Uso internacional',
'enabled' => 'Habilitado',
'security' => 'Seguridad',
'pci_dss_standard' => 'Estándar PCI DSS',
'select_account' => 'Seleccione una cuenta',
'please_select_account' => 'Por favor seleccione una cuenta asociada.',
'account_card_association_info' => 'Esta cuenta será asociada a la tarjeta para transacciones',
'select_option' => 'Seleccione una opción',
'please_select_card_type' => 'Por favor seleccione el tipo de tarjeta.',
'please_enter_valid_card_number' => 'Por favor ingrese un número de tarjeta válido.',
'card_number_format_help' => 'Ingrese los 16 dígitos de la tarjeta separados en grupos de 4',
'cvv_tooltip' => 'Código de seguridad de 3 dígitos ubicado en el reverso de la tarjeta',
'secure_field' => 'Campo seguro',
'cvv_validation' => 'El CVV debe tener 3 dígitos.',
'cvv_help' => 'Código de seguridad de 3 dígitos',
'expiration_date_validation' => 'Por favor ingrese una fecha válida (MM/YY).',
'expiration_date_format' => 'Formato: MM/YY (ejemplo: 12/25)',
'pin_tooltip' => 'Código secreto de 4 dígitos para usar en cajeros y comercios',
'show_hide_pin' => 'Mostrar/Ocultar PIN',
'pin_validation' => 'El PIN debe tener 4 dígitos.',
'pin_help' => 'Código numérico de 4 dígitos',
'security_measures' => 'Medidas de Seguridad',
'last_modification' => 'Última Modificación',
'security_notice' => 'Aviso de Seguridad',
'security_notice_text' => 'Todo cambio en la información de la tarjeta quedará registrado y podría requerir verificación adicional. El cambio del PIN o bloqueo de la tarjeta se aplicará inmediatamente.',
'save_changes' => 'Guardar Cambios',
'cancel' => 'Cancelar',
'block_card' => 'Bloquear Tarjeta',




// Nueva Tarjeta
'new_card' => 'Nueva Tarjeta',
'account' => 'Cuenta',
'type' => 'Tipo',
'number' => 'Número',
'select_card_type' => 'Seleccione el tipo de tarjeta',
'card_number_required' => 'El número de tarjeta es requerido',
'auto_generated_number' => 'El número se genera automáticamente',
'cvv_required' => 'El CVV es requerido',
'expiration_date_required' => 'La fecha de vencimiento es requerida',
'expiration_date_format_short' => 'Formato: MM/AA',
'pin_required' => 'El PIN es requerido',
'pin_digits_info' => 'Debe contener 4 dígitos numéricos',
'select_status' => 'Seleccione un estado',
'additional_information' => 'Información Adicional',
'credit_limit' => 'Límite de Crédito',
'credit_limit_info' => 'Límite máximo para tarjetas de crédito',
'notes' => 'Notas',
'additional_card_info' => 'Información adicional sobre la tarjeta (opcional)',
'save' => 'Guardar',







//SECCCION DE CLIENTES

// Lista de Clientes
'client_list' => 'Lista de Clientes',
'new_client' => 'Nuevo Cliente',
'no_clients_registered' => 'No hay clientes registrados en el sistema.',
'identity_card' => 'Cédula de Identidad',
'name' => 'Nombre',
'paternal_surname' => 'Apellido Paterno',
'maternal_surname' => 'Apellido Materno',
'phone' => 'Teléfono',
'office' => 'Oficina',
'actions' => 'Acciones',
'view_details' => 'Ver detalles',
'edit' => 'Editar',
'delete' => 'Eliminar',


// Crear Cliente
'new_client' => 'Nuevo Cliente',
'name' => 'Nombre',
'name_required' => 'El nombre es requerido',
'paternal_last_name' => 'Apellido Paterno',
'paternal_last_name_required' => 'El apellido paterno es requerido',
'maternal_last_name' => 'Apellido Materno',
'address' => 'Dirección',
'phone' => 'Teléfono',
'email' => 'Email',
'valid_email_required' => 'Ingrese un email válido',
'birth_date' => 'Fecha de Nacimiento',
'id_number' => 'Cédula de Identidad',
'id_number_required' => 'La cédula de identidad es requerida',
'branch' => 'Oficina',
'branch_required' => 'La oficina es requerida',
'save' => 'Guardar',
'cancel' => 'Cancelar',
'select_option' => 'Seleccione una opción',



// Ver Cliente
'client_details' => 'Detalles de Cliente',
'view_mode' => 'Modo Visualización',
'id_short' => 'CI',
'client_id' => 'ID Cliente',
'identity_document' => 'CI / Documento',
'registration_date' => 'Fecha de Registro',
'client_type' => 'Tipo de Cliente',
'personal' => 'Personal',
'business' => 'Empresarial',
'bank_accounts' => 'Cuentas Bancarias',
'new_account' => 'Nueva Cuenta',
'no_accounts' => 'No hay cuentas asociadas a este cliente.',
'create_account' => 'Crear Cuenta',
'account_number' => 'Nro. Cuenta',
'currency' => 'Moneda',
'balance' => 'Saldo',
'opening_date' => 'Fecha Apertura',
'savings' => 'Ahorro',
'checking' => 'Corriente',
'bolivianos' => 'Bolivianos (Bs)',
'dollars' => 'Dólares ($)',
'view' => 'Ver',
'deposit' => 'Depositar',
'withdraw' => 'Retirar',
'recent_transactions' => 'Últimas Transacciones',
'view_all' => 'Ver todas',
'no_transactions' => 'No hay transacciones registradas para este cliente.',
'date' => 'Fecha',
'time' => 'Hora',
'account' => 'Cuenta',
'description' => 'Descripción',
'amount' => 'Monto',
'withdrawal' => 'Retiro',
'received_transfer' => 'Transferencia Recibida',
'sent_transfer' => 'Transferencia Enviada',
'other' => 'Otro',
'deactivate' => 'Desactivar',
'activate' => 'Activar',
'back_to_list' => 'Volver a la Lista',
'confirm_deactivate_client' => '¿Está seguro que desea desactivar este cliente?',
'confirm_activate_client' => '¿Está seguro que desea activar este cliente?',







//SECCION DE CUENTAS

// Ver Cuenta
'account_details' => 'Detalles de Cuenta',
'view_mode' => 'Modo Visualización',
'deposit' => 'Depositar',
'withdraw' => 'Retirar',
'transfer' => 'Transferir',
'statement' => 'Extracto',
'account_information' => 'Información de la Cuenta',
'account_number' => 'Número de Cuenta',
'account_type' => 'Tipo de Cuenta',
'savings_account' => 'Cuenta de Ahorro',
'checking_account' => 'Cuenta Corriente',
'currency' => 'Moneda',
'current_balance' => 'Saldo Actual',
'opening_date' => 'Fecha de Apertura',
'status' => 'Estado',
'active' => 'Activa',
'inactive' => 'Inactiva',
'client_information' => 'Información del Cliente',
'surnames' => 'Apellidos',
'identity_document' => 'CI / Documento',
'view_client' => 'Ver Cliente',
'view_client_details' => 'Ver detalles del cliente',
'recent_transactions' => 'Transacciones Recientes',
'view_full_statement' => 'Ver Extracto Completo',
'no_transactions_account' => 'No hay transacciones registradas para esta cuenta.',
'date' => 'Fecha',
'time' => 'Hora',
'type' => 'Tipo',
'description' => 'Descripción',
'amount' => 'Monto',
'resulting_balance' => 'Saldo Resultante',
'withdrawal' => 'Retiro',
'received_transfer' => 'Transferencia Recibida',
'sent_transfer' => 'Transferencia Enviada',
'other' => 'Otro',
'view_all_transactions' => 'Ver todas las transacciones',
'edit' => 'Editar',
'close_account' => 'Cerrar Cuenta',
'reactivate_account' => 'Reactivar Cuenta',
'back_to_list' => 'Volver a la Lista',
'confirm_close_account' => '¿Está seguro que desea cerrar esta cuenta?',
'confirm_reactivate_account' => '¿Está seguro que desea reactivar esta cuenta?',



// Lista de Cuentas
'account_list' => 'Lista de Cuentas',
'new_account' => 'Nueva Cuenta',
'no_accounts_registered' => 'No hay cuentas registradas en el sistema.',
'account_number' => 'Número de Cuenta',
'client' => 'Cliente',
'account_type' => 'Tipo de Cuenta',
'currency' => 'Moneda',
'balance' => 'Saldo',
'opening_date' => 'Fecha de Apertura',
'status' => 'Estado',
'savings' => 'Ahorro',
'checking' => 'Corriente',
'bolivianos_short' => 'Bolivianos',
'dollars_short' => 'Dólares',
'active' => 'Activa',
'inactive' => 'Inactiva',
'view_details' => 'Ver detalles',
'edit' => 'Editar',
'deposit' => 'Depositar',
'withdraw' => 'Retirar',



// Crear Cuenta
'new_account' => 'Nueva Cuenta',
'client' => 'Cliente',
'select_client' => 'Seleccione un cliente',
'client_required' => 'El cliente es requerido',
'account_type' => 'Tipo de Cuenta',
'account_type_required' => 'El tipo de cuenta es requerido',
'savings_account' => 'Cuenta de Ahorro',
'checking_account' => 'Cuenta Corriente',
'currency' => 'Moneda',
'currency_required' => 'La moneda es requerida',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dólares',
'initial_balance' => 'Saldo Inicial',
'initial_balance_help' => 'Saldo con el que se iniciará la cuenta',
'save' => 'Guardar',
'cancel' => 'Cancelar',
'select_option' => 'Seleccione una opción',


// Editar Cuenta
'edit_account' => 'Editar Cuenta',
'editing_mode' => 'Modo Edición',
'account_number' => 'Número de Cuenta',
'client' => 'Cliente',
'currency' => 'Moneda',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dólares',
'balance' => 'Saldo',
'opening_date' => 'Fecha de Apertura',
'account_type' => 'Tipo de Cuenta',
'savings_account' => 'Cuenta de Ahorro',
'checking_account' => 'Cuenta Corriente',
'account_type_required' => 'El tipo de cuenta es requerido',
'status' => 'Estado',
'active' => 'Activa',
'inactive' => 'Inactiva',
'status_required' => 'El estado es requerido',
'save' => 'Guardar',
'cancel' => 'Cancelar',



//SECCION DE TRANSACCIONES

// Lista de Transacciones
'transaction_list' => 'Lista de Transacciones',
'search_transactions' => 'Buscar Transacciones',
'withdrawal' => 'Retiro',
'deposit' => 'Depósito',
'print' => 'Imprimir',
'no_transactions' => 'No hay transacciones registradas en el sistema.',
'date' => 'Fecha',
'time' => 'Hora',
'transaction_type' => 'Tipo de Transacción',
'account_number' => 'Número de Cuenta',
'client' => 'Cliente',
'description' => 'Descripción',
'amount' => 'Monto',
'actions' => 'Acciones',
'transfer_received' => 'Transferencia Recibida',
'transfer_sent' => 'Transferencia Enviada',
'other' => 'Otro',
'view' => 'Ver',
'receipt' => 'Comprobante',




// Ver Transacción
'transaction_details' => 'Detalles de Transacción',
'view_mode' => 'Modo Visualización',
'withdrawal' => 'Retiro',
'deposit' => 'Depósito',
'transfer_received' => 'Transferencia Recibida',
'transfer_sent' => 'Transferencia Enviada',
'other_operation' => 'Otra Operación',
'transaction_id_with_number' => 'Transacción #%s',
'date_time_format' => '%s a las %s',
'transaction_information' => 'Información de la Transacción',
'transaction_id' => 'ID Transacción',
'transaction_type' => 'Tipo de Transacción',
'date' => 'Fecha',
'time' => 'Hora',
'amount' => 'Monto',
'resulting_balance' => 'Saldo Resultante',
'description' => 'Descripción',
'source_account' => 'Cuenta Origen',
'destination_account' => 'Cuenta Destino',
'account_information' => 'Información de la Cuenta',
'account_number' => 'Número de Cuenta',
'account_type' => 'Tipo de Cuenta',
'savings' => 'Ahorro',
'checking' => 'Corriente',
'currency' => 'Moneda',
'bolivianos' => 'Bolivianos (Bs)',
'dollars' => 'Dólares ($)',
'client_information' => 'Información del Cliente',
'full_name' => 'Nombre Completo',
'identity_document' => 'CI / Documento',
'print_receipt' => 'Imprimir Comprobante',
'back_to_list' => 'Volver a la Lista',



// Comprobante de Transacción
'transaction_receipt' => 'Comprobante de Transacción',
'bank_name' => 'Banco Mercantil',
'receipt' => 'COMPROBANTE',
'transaction_receipt_title' => 'COMPROBANTE DE TRANSACCIÓN',
'id' => 'ID',
'withdrawal_receipt' => 'COMPROBANTE DE RETIRO',
'deposit_receipt' => 'COMPROBANTE DE DEPÓSITO',
'transfer_received_receipt' => 'COMPROBANTE DE TRANSFERENCIA RECIBIDA',
'transfer_sent_receipt' => 'COMPROBANTE DE TRANSFERENCIA ENVIADA',
'receipt_security_message' => 'Este documento es un comprobante oficial de Banco Mercantil. Verifique los datos antes de finalizar.',
'branch' => 'Sucursal',
'head_office' => 'Casa Matriz',
'attended_by' => 'Atendido por',
'online_transaction' => 'Transacción en línea',
'verification_qr_code' => 'Código QR de verificación',
'scan_qr_code' => 'Escanee el código QR para verificar la autenticidad',
'transaction_reference' => 'Referencia',
'receipt_thank_you' => '¡Gracias por confiar en Banco Mercantil!',
'receipt_valid_without_signature' => 'Este comprobante es válido sin firma ni sello.',
'receipt_contact_info' => 'Para cualquier consulta, comuníquese al 0800-BANCO (22626)',
'generated_on' => 'Generado el',
'print' => 'Imprimir',
'back' => 'Volver',
'download_pdf' => 'Descargar PDF',
'send_by_email' => 'Enviar por Email',
'report_issue' => 'Reportar',
'verification_seal' => 'Sello de verificación',
'pdf_download_started' => 'Descarga de PDF iniciada...',
'enter_email' => 'Por favor, ingrese su dirección de correo electrónico:',
'email_sent' => 'Comprobante enviado al correo electrónico.',
'describe_issue' => 'Por favor, describa el problema:',
'issue_reported' => 'Problema reportado. Gracias por su retroalimentación.',



// Búsqueda de Transacciones
'transaction_search' => 'Búsqueda de Transacciones',
'account' => 'Cuenta',
'all_accounts' => 'Todas las cuentas',
'all_types' => 'Todos los tipos',
'start_date' => 'Fecha Inicio',
'end_date' => 'Fecha Fin',
'search' => 'Buscar',
'search_results' => 'Resultados de la Búsqueda',
'type' => 'Tipo',
'atm_withdrawal' => 'Retiro en cajero',
'counter_deposit' => 'Depósito en ventanilla',
'view' => 'Ver',
'receipt' => 'Comprobante',
'advanced_options' => 'Opciones avanzadas',
'hide_advanced' => 'Ocultar opciones avanzadas',
'min_amount' => 'Monto mínimo',
'max_amount' => 'Monto máximo',
'description_contains' => 'Descripción contiene',
'previous_page' => 'Página anterior',
'next_page' => 'Página siguiente',
'page' => 'Página',
'of' => 'de',
'print' => 'Imprimir',
'back' => 'Volver',
'export' => 'Exportar',
'export_as' => 'Exportar como',
'excel' => 'Excel',
'pdf' => 'PDF',
'csv' => 'CSV',
'exporting' => 'Exportando',


// Retiro de Fondos
'withdrawal' => 'Retiro de Fondos',
'bank_name' => 'Banco Mercantil',
'enter_account_number_to_withdraw' => 'Ingrese el número de cuenta del cual desea realizar el retiro.',
'account_number' => 'Número de Cuenta',
'enter_account_number' => 'Ingrese el número de cuenta',
'search' => 'Buscar',
'cancel' => 'Cancelar',
'account_information' => 'Información de la Cuenta',
'account_type' => 'Tipo de Cuenta',
'savings_account' => 'Cuenta de Ahorros',
'checking_account' => 'Cuenta Corriente',
'currency' => 'Moneda',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dólares',
'available_balance' => 'Saldo Disponible',
'client_information' => 'Información del Cliente',
'name' => 'Nombre',
'last_name' => 'Apellido',
'id_number' => 'Número de Identificación',
'amount' => 'Monto',
'amount_required' => 'Por favor ingrese un monto válido.',
'max_amount' => 'Monto máximo',
'description' => 'Descripción',
'cash_withdrawal' => 'Retiro de efectivo',
'withdraw' => 'Retirar',
'where_find_account_number' => '¿Dónde encontrar mi número de cuenta?',
'account_number_locations' => 'Su número aparece en la libreta, tarjeta de débito o app móvil',
'verify_available_balance' => 'Verificar saldo disponible',
'ensure_sufficient_funds' => 'Asegúrese de tener fondos suficientes antes de retirar',
'account_authorization' => 'Autorización de cuentas',
'account_authorization_info' => 'Solo puede retirar de cuentas donde es titular o tiene autorización',
'withdrawal_limits' => 'Límites de retiro',
'max_amount_depends' => 'El monto máximo depende del tipo de cuenta y saldo disponible',
'example_accounts' => 'Ejemplos de Cuentas',
'savings' => 'Ahorros',
'personal_account' => 'Cuenta Personal',
'checking' => 'Corriente',
'business_account' => 'Cuenta Empresarial',
'payroll' => 'Nómina',
'salary_account' => 'Cuenta Salario',





// Depósito de Fondos
'deposit_funds' => 'Depósito de Fondos',
'bank_name' => 'Banco Mercantil',
'enter_account_number_to_deposit' => 'Ingrese el número de cuenta en la cual desea realizar el depósito.',
'account_number' => 'Número de Cuenta',
'enter_account_number' => 'Ingrese el número de cuenta',
'search' => 'Buscar',
'cancel' => 'Cancelar',
'account_information' => 'Información de la Cuenta',
'account_type' => 'Tipo de Cuenta',
'savings_account' => 'Cuenta de Ahorros',
'checking_account' => 'Cuenta Corriente',
'currency' => 'Moneda',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dólares',
'client_information' => 'Información del Cliente',
'name' => 'Nombre',
'last_name' => 'Apellido',
'id_number' => 'Número de Identificación',
'amount' => 'Monto',
'amount_required' => 'Por favor ingrese un monto válido.',
'description' => 'Descripción',
'cash_deposit' => 'Depósito de efectivo',
'deposit' => 'Depositar',
'where_find_account_number' => '¿Dónde encontrar el número de cuenta?',
'account_number_locations' => 'El número aparece en la libreta, tarjeta de débito o app móvil',
'deposit_types' => 'Tipos de depósito',
'deposit_types_info' => 'Puede realizar depósitos en efectivo, cheque o transferencia',
'deposit_limits' => 'Límites de depósito',
'deposit_limits_info' => 'Consulte los límites según el tipo de cuenta y canal utilizado',
'crediting_time' => 'Tiempo de acreditación',
'crediting_time_info' => 'Los depósitos en efectivo se acreditan de inmediato',
'example_accounts' => 'Ejemplos de Cuentas',
'savings' => 'Ahorros',
'personal_account' => 'Cuenta Personal',
'checking' => 'Corriente',
'business_account' => 'Cuenta Empresarial',
'payroll' => 'Nómina',
'salary_account' => 'Cuenta Salario',



// Reportes
'reports' => 'Reportes',
'print' => 'Imprimir',
'note' => 'Nota',
'reports_note' => 'Los reportes se generan en tiempo real con datos actualizados del sistema.',
'transactions_stats_reports' => 'Reportes de Transacciones y Estadísticas',
'report_name' => 'Nombre del Reporte',
'description' => 'Descripción',
'actions' => 'Acciones',
'transactions_by_date' => 'Transacciones por Fecha',
'transactions_by_date_desc' => 'Informe detallado de transacciones realizadas en un rango de fechas seleccionado.',
'view_report' => 'Ver Reporte',
'transactions_by_client' => 'Transacciones por Cliente',
'transactions_by_client_desc' => 'Historial de transacciones agrupadas por cliente para un análisis detallado de actividad.',
'atm_statistics' => 'Estadísticas de ATM',
'atm_statistics_desc' => 'Análisis de uso de cajeros automáticos, transacciones y disponibilidad.',
'balances_activity_reports' => 'Reportes de Saldos y Actividad',
'balances_by_branch' => 'Saldos por Oficina',
'balances_by_branch_desc' => 'Reporte de saldos consolidados por oficina y tipo de cuenta.',
'account_activity' => 'Actividad de Cuenta',
'account_activity_desc' => 'Historial detallado de actividades para todas las cuentas en un período seleccionado.',
'executive_summary' => 'Resumen Ejecutivo',
'executive_summary_desc' => 'Resumen general de estadísticas e indicadores clave para la gerencia.',
'performance_audit_reports' => 'Reportes de Rendimiento y Auditoría',
'product_performance' => 'Rendimiento por Producto',
'product_performance_desc' => 'Análisis de rendimiento para cada producto financiero ofrecido por el banco.',
'system_audit' => 'Auditoría del Sistema',
'system_audit_desc' => 'Registro de todas las operaciones y cambios realizados en el sistema por usuario.',
'service_metrics' => 'Métricas de Servicio',
'service_metrics_desc' => 'Estadísticas de calidad de servicio y satisfacción del cliente en todas las sucursales.',




// Lista de Oficinas
'branch_list' => 'Lista de Oficinas',
'new_branch' => 'Nueva Oficina',
'no_branches_found' => 'No hay oficinas registradas en el sistema.',
'name' => 'Nombre',
'address' => 'Dirección',
'city' => 'Ciudad',
'phone' => 'Teléfono',
'type' => 'Tipo',
'status' => 'Estado',
'actions' => 'Acciones',
'central' => 'Central',
'branch' => 'Sucursal',
'active' => 'Activa',
'inactive' => 'Inactiva',
'view' => 'Ver',
'edit' => 'Editar',
'deactivate' => 'Desactivar',
'activate' => 'Activar',
'delete' => 'Eliminar',
'confirm_deactivate_branch' => '¿Está seguro que desea desactivar esta oficina?',
'confirm_activate_branch' => '¿Está seguro que desea activar esta oficina?',
'confirm_delete_branch' => '¿Está seguro que desea eliminar esta oficina? Esta acción no se puede deshacer.',

// Editar Oficina
'edit_office' => 'Editar Oficina',
'editing_mode' => 'Modo Edición',
'name_required' => 'El nombre es requerido',
'address_required' => 'La dirección es requerida',
'city_required' => 'La ciudad es requerida',
'state' => 'Departamento',
'state_required' => 'El departamento es requerido',
'country' => 'País',
'country_required' => 'El país es requerido',
'office_hours' => 'Horario de Atención',
'office_hours_placeholder' => 'Ej: Lunes a Viernes 8:00 - 16:00',
'manager' => 'Gerente Encargado',
'opening_date' => 'Fecha de Inauguración',
'branch_type' => 'Tipo de Oficina',
'save' => 'Guardar',
'cancel' => 'Cancelar',




// CREAR OFICINA
'new_branch' => 'Nueva Oficina',
'name_required' => 'El nombre es obligatorio',
'address_required' => 'La dirección es obligatoria',
'office_hours_placeholder' => 'Ej: Lunes a Viernes: 8:30 - 16:30, Sábados: 8:30 - 12:30',





// Ver Oficina
'branch_details' => 'Detalles de Oficina',
'view_mode' => 'Modo Visualización',
'id' => 'ID',
'central' => 'Central',
'branch' => 'Sucursal',
'active' => 'Activa',
'inactive' => 'Inactiva',
'general_information' => 'Información General',
'name' => 'Nombre',
'address' => 'Dirección',
'city' => 'Ciudad',
'state' => 'Departamento',
'country' => 'País',
'phone' => 'Teléfono',
'office_hours' => 'Horario de Atención',
'manager' => 'Gerente Encargado',
'opening_date' => 'Fecha de Inauguración',
'branch_type' => 'Tipo de Oficina',
'status' => 'Estado',
'employees' => 'Empleados',
'new_employee' => 'Nuevo Empleado',
'no_employees' => 'No hay empleados asignados a esta oficina.',
'add_employee' => 'Agregar Empleado',
'position' => 'Cargo',
'email' => 'Correo electrónico',
'actions' => 'Acciones',
'view' => 'Ver',
'edit' => 'Editar',
'back_to_list' => 'Volver a la Lista',
'deactivate' => 'Desactivar',
'activate' => 'Activar',
'confirm_deactivate' => '¿Está seguro que desea desactivar esta oficina?',
'confirm_activate' => '¿Está seguro que desea activar esta oficina?',




// Lista de Transacciones ATM
'atm_transaction_list' => 'Listado de Transacciones ATM',
'search_atm_transactions' => 'Buscar Transacciones ATM',
'withdrawal' => 'Retiro',
'deposit' => 'Depósito',
'no_transactions' => 'No hay transacciones registradas en el sistema.',
'date' => 'Fecha',
'time' => 'Hora',
'transaction_type' => 'Tipo',
'description' => 'Descripción',
'account_number' => 'Nro. Cuenta',
'amount' => 'Monto',
'resulting_balance' => 'Saldo Resultante',
'client' => 'Cliente',
'atm' => 'Cajero',
'actions' => 'Acciones',
'inquiry' => 'Consulta',
'other' => 'Otro',
'view' => 'Ver',
'receipt' => 'Comprobante',
'print' => 'Imprimir',
];
?>

