/*
 * Formulario Principal - Juego de Ajedrez Completo
 * Interfaz gráfica que conecta con la lógica del juego
 */
package presentacion;

import negocio.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.Timer;
import java.util.ArrayList;

/**
 *
 * @author dell
 */
public class frmAjedrez extends javax.swing.JFrame {

    // Lógica del juego
    private clsPartidaAjedrez partida;
    private clsIA inteligenciaArtificial;

    // Configuración del juego
    private String modoJuego; // "1_JUGADOR" o "2_JUGADORES"
    private String dificultadIA; // "FACIL", "MEDIO", "DIFICIL"
    private boolean turnoIA = false;

    // Tablero visual
    private JButton[][] botonesTablero;

    // Control de selección
    private int filaSeleccionada = -1;
    private int columnaSeleccionada = -1;
    private ArrayList<int[]> movimientosPosibles;

    // Colores del tablero
    private final Color COLOR_CASILLA_CLARA = new Color(240, 217, 181);
    private final Color COLOR_CASILLA_OSCURA = new Color(181, 136, 99);
    private final Color COLOR_SELECCIONADA = new Color(255, 255, 0, 150);
    private final Color COLOR_MOVIMIENTO_POSIBLE = new Color(0, 255, 0, 100);
    private final Color COLOR_JAQUE = new Color(255, 0, 0, 150);

    /**
     * Creates new form frmAjedrez
     */
    public frmAjedrez() {
        initComponents();
        inicializarJuego();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        panelTurno = new javax.swing.JPanel();
        lblTurno = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        panelCapturadasBlancas = new javax.swing.JPanel();
        lblPuntuacionBlancas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCapturadasBlancas = new javax.swing.JTextArea();
        panelCapturadasNegras = new javax.swing.JPanel();
        lblPuntuacionNegras = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCapturadasNegras = new javax.swing.JTextArea();
        btnIniciarJuego = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        btnRendirse = new javax.swing.JButton();
        panelTablero = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHistorial = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajedrez - TDA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(63, 81, 181));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("♔ AJEDREZ ♚");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        panelIzquierdo.setBackground(new java.awt.Color(245, 245, 245));
        panelIzquierdo.setPreferredSize(new java.awt.Dimension(220, 650));

        panelTurno.setBackground(new java.awt.Color(255, 255, 255));
        panelTurno.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno Actual"));
        panelTurno.setPreferredSize(new java.awt.Dimension(200, 100));

        lblTurno.setFont(new java.awt.Font("Segoe UI", 1, 16));
        lblTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurno.setText("Blancas");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 2, 12));
        lblEstado.setForeground(new java.awt.Color(0, 0, 255));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTurnoLayout = new javax.swing.GroupLayout(panelTurno);
        panelTurno.setLayout(panelTurnoLayout);
        panelTurnoLayout.setHorizontalGroup(
            panelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTurnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTurnoLayout.setVerticalGroup(
            panelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTurnoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelCapturadasBlancas.setBackground(new java.awt.Color(255, 255, 255));
        panelCapturadasBlancas.setBorder(javax.swing.BorderFactory.createTitledBorder("Capturadas por Blancas"));
        panelCapturadasBlancas.setPreferredSize(new java.awt.Dimension(200, 120));

        lblPuntuacionBlancas.setFont(new java.awt.Font("Segoe UI", 1, 11));
        lblPuntuacionBlancas.setText("Puntuación: 0");

        txtCapturadasBlancas.setEditable(false);
        txtCapturadasBlancas.setColumns(20);
        txtCapturadasBlancas.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18));
        txtCapturadasBlancas.setLineWrap(true);
        txtCapturadasBlancas.setRows(2);
        txtCapturadasBlancas.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtCapturadasBlancas);

        javax.swing.GroupLayout panelCapturadasBlancasLayout = new javax.swing.GroupLayout(panelCapturadasBlancas);
        panelCapturadasBlancas.setLayout(panelCapturadasBlancasLayout);
        panelCapturadasBlancasLayout.setHorizontalGroup(
            panelCapturadasBlancasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCapturadasBlancasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCapturadasBlancasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addGroup(panelCapturadasBlancasLayout.createSequentialGroup()
                        .addComponent(lblPuntuacionBlancas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCapturadasBlancasLayout.setVerticalGroup(
            panelCapturadasBlancasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCapturadasBlancasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuntuacionBlancas)
                .addContainerGap())
        );

        panelCapturadasNegras.setBackground(new java.awt.Color(255, 255, 255));
        panelCapturadasNegras.setBorder(javax.swing.BorderFactory.createTitledBorder("Capturadas por Negras"));
        panelCapturadasNegras.setPreferredSize(new java.awt.Dimension(200, 120));

        lblPuntuacionNegras.setFont(new java.awt.Font("Segoe UI", 1, 11));
        lblPuntuacionNegras.setText("Puntuación: 0");

        txtCapturadasNegras.setEditable(false);
        txtCapturadasNegras.setColumns(20);
        txtCapturadasNegras.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18));
        txtCapturadasNegras.setLineWrap(true);
        txtCapturadasNegras.setRows(2);
        txtCapturadasNegras.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtCapturadasNegras);

        javax.swing.GroupLayout panelCapturadasNegrasLayout = new javax.swing.GroupLayout(panelCapturadasNegras);
        panelCapturadasNegras.setLayout(panelCapturadasNegrasLayout);
        panelCapturadasNegrasLayout.setHorizontalGroup(
            panelCapturadasNegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCapturadasNegrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCapturadasNegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addGroup(panelCapturadasNegrasLayout.createSequentialGroup()
                        .addComponent(lblPuntuacionNegras)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCapturadasNegrasLayout.setVerticalGroup(
            panelCapturadasNegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCapturadasNegrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuntuacionNegras)
                .addContainerGap())
        );

        btnIniciarJuego.setBackground(new java.awt.Color(0, 193, 156));
        btnIniciarJuego.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnIniciarJuego.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarJuego.setText("▶ INICIAR JUEGO");
        btnIniciarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarJuego.setFocusPainted(false);
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });

        btnReiniciar.setBackground(new java.awt.Color(76, 175, 80));
        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciar.setText("🔄 Reiniciar");
        btnReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReiniciar.setFocusPainted(false);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnDeshacer.setBackground(new java.awt.Color(33, 150, 243));
        btnDeshacer.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacer.setText("↶ Deshacer");
        btnDeshacer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeshacer.setFocusPainted(false);
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });

        btnRendirse.setBackground(new java.awt.Color(244, 67, 54));
        btnRendirse.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnRendirse.setForeground(new java.awt.Color(255, 255, 255));
        btnRendirse.setText("🏳 Rendirse");
        btnRendirse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRendirse.setFocusPainted(false);
        btnRendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendirseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdoLayout = new javax.swing.GroupLayout(panelIzquierdo);
        panelIzquierdo.setLayout(panelIzquierdoLayout);
        panelIzquierdoLayout.setHorizontalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCapturadasBlancas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCapturadasNegras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIniciarJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeshacer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRendirse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelIzquierdoLayout.setVerticalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCapturadasBlancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCapturadasNegras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeshacer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRendirse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTablero.setBackground(new java.awt.Color(245, 245, 245));
        panelTablero.setPreferredSize(new java.awt.Dimension(650, 650));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelDerecho.setBackground(new java.awt.Color(245, 245, 245));
        panelDerecho.setPreferredSize(new java.awt.Dimension(250, 650));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel2.setText("Historial de Movimientos");

        txtHistorial.setEditable(false);
        txtHistorial.setColumns(20);
        txtHistorial.setFont(new java.awt.Font("Consolas", 0, 12));
        txtHistorial.setRows(5);
        jScrollPane3.setViewportView(txtHistorial);

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(panelDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAjedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAjedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAjedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAjedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAjedrez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnRendirse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblPuntuacionBlancas;
    private javax.swing.JLabel lblPuntuacionNegras;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JPanel panelCapturadasBlancas;
    private javax.swing.JPanel panelCapturadasNegras;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JPanel panelTurno;
    private javax.swing.JTextArea txtCapturadasBlancas;
    private javax.swing.JTextArea txtCapturadasNegras;
    private javax.swing.JTextArea txtHistorial;
    // End of variables declaration//GEN-END:variables

    // ==================== MÉTODOS PERSONALIZADOS ====================

    /**
     * Inicializar el juego y crear el tablero visual (sin iniciar partida)
     */
    private void inicializarJuego() {
        // Crear una partida vacía por defecto (sin jugar aún)
        partida = new clsPartidaAjedrez("Jugador 1", "Jugador 2");
        modoJuego = null; // Aún no se ha seleccionado modo

        // Crear el tablero visual
        crearTableroVisual();

        // Deshabilitar el tablero hasta que se presione "Iniciar Juego"
        deshabilitarTablero();

        // Actualizar la interfaz
        actualizarInterfaz();
    }

    /**
     * Iniciar una nueva partida (llamado por el botón "Iniciar Juego")
     */
    private void iniciarNuevaPartida() {
        // Mostrar diálogo de selección de modo
        mostrarDialogoModoJuego();

        // Si el usuario canceló, no hacer nada
        if (modoJuego == null) {
            return;
        }

        // Crear la partida según el modo seleccionado
        if (modoJuego.equals("1_JUGADOR")) {
            partida = new clsPartidaAjedrez("Jugador", "Computadora");
            inteligenciaArtificial = new clsIA("NEGRO", dificultadIA);
        } else {
            partida = new clsPartidaAjedrez("Jugador 1", "Jugador 2");
            inteligenciaArtificial = null;
        }

        // Limpiar selección
        filaSeleccionada = -1;
        columnaSeleccionada = -1;
        movimientosPosibles = null;

        // Habilitar el tablero
        habilitarTablero();

        // Actualizar la interfaz
        actualizarInterfaz();
    }

    /**
     * Mostrar diálogo para seleccionar modo de juego
     */
    private void mostrarDialogoModoJuego() {
        Object[] opciones = {"1 Jugador (vs IA)", "2 Jugadores"};
        int seleccion = JOptionPane.showOptionDialog(
                this,
                "Selecciona el modo de juego:",
                "Modo de Juego",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        if (seleccion == 0) {
            modoJuego = "1_JUGADOR";
            // Seleccionar dificultad
            mostrarDialogoDificultad();
        } else if (seleccion == 1) {
            modoJuego = "2_JUGADORES";
            dificultadIA = null;
        } else {
            // Usuario canceló
            modoJuego = null;
        }
    }

    /**
     * Mostrar diálogo para seleccionar dificultad de la IA
     */
    private void mostrarDialogoDificultad() {
        Object[] opciones = {"Fácil", "Medio", "Difícil"};
        int seleccion = JOptionPane.showOptionDialog(
                this,
                "Selecciona la dificultad:",
                "Dificultad de la IA",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[1]
        );

        switch (seleccion) {
            case 0:
                dificultadIA = "FACIL";
                break;
            case 1:
                dificultadIA = "MEDIO";
                break;
            case 2:
                dificultadIA = "DIFICIL";
                break;
            default:
                dificultadIA = "MEDIO";
        }
    }

    /**
     * Crear el tablero de 8x8 botones
     */
    private void crearTableroVisual() {
        // Configurar el panel del tablero con GridLayout
        panelTablero.setLayout(new GridLayout(8, 8, 0, 0));
        panelTablero.setBackground(Color.BLACK);

        botonesTablero = new JButton[8][8];

        for (int fila = 0; fila < 8; fila++) {
            for (int columna = 0; columna < 8; columna++) {
                final int f = fila;
                final int c = columna;

                // Crear botón personalizado que pinta su propio fondo
                JButton boton = new JButton() {
                    @Override
                    protected void paintComponent(Graphics g) {
                        // Pintar el fondo con el color asignado
                        g.setColor(getBackground());
                        g.fillRect(0, 0, getWidth(), getHeight());

                        // Establecer color del texto antes de pintar
                        g.setColor(getForeground());

                        // Llamar al método padre para dibujar el texto
                        super.paintComponent(g);
                    }
                };

                boton.setFont(new Font("Segoe UI Symbol", Font.PLAIN, 48));
                boton.setForeground(Color.BLACK); // Color de las piezas
                boton.setFocusPainted(false);
                boton.setBorderPainted(false);
                boton.setOpaque(true);
                boton.setContentAreaFilled(false); // Importante: desactivar el relleno por defecto

                // Deshabilitar efectos visuales
                boton.setRolloverEnabled(false);

                // Color de la casilla (patrón de ajedrez)
                if ((fila + columna) % 2 == 0) {
                    boton.setBackground(COLOR_CASILLA_CLARA);
                } else {
                    boton.setBackground(COLOR_CASILLA_OSCURA);
                }

                // Agregar listener
                boton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        casillaClickeada(f, c);
                    }
                });

                botonesTablero[fila][columna] = boton;
                panelTablero.add(boton);
            }
        }

        // Actualizar piezas en el tablero
        actualizarTableroVisual();
    }

    /**
     * Actualizar las piezas en el tablero visual
     */
    private void actualizarTableroVisual() {
        clsPieza[][] tablero = partida.getTablero().getTablero();

        for (int fila = 0; fila < 8; fila++) {
            for (int columna = 0; columna < 8; columna++) {
                JButton boton = botonesTablero[fila][columna];
                clsPieza pieza = tablero[fila][columna];

                // Actualizar texto (pieza)
                if (pieza != null) {
                    boton.setText(pieza.getSimbolo());
                } else {
                    boton.setText("");
                }

                // Restaurar color original del tablero
                Color colorOriginal;
                if ((fila + columna) % 2 == 0) {
                    colorOriginal = COLOR_CASILLA_CLARA;
                } else {
                    colorOriginal = COLOR_CASILLA_OSCURA;
                }

                // Solo cambiar el color si es diferente (evita repintado innecesario)
                if (!boton.getBackground().equals(colorOriginal)) {
                    boton.setBackground(colorOriginal);
                }
            }
        }

        // Resaltar rey en jaque
        if (partida.getJugadorActual().isEnJaque()) {
            String colorRey = partida.getJugadorActual().getColor();
            int[] posRey = partida.getTablero().buscarRey(colorRey);
            if (posRey != null) {
                botonesTablero[posRey[0]][posRey[1]].setBackground(COLOR_JAQUE);
            }
        }
    }

    /**
     * Manejar clic en una casilla
     */
    private void casillaClickeada(int fila, int columna) {
        if (partida.isPartidaTerminada()) {
            JOptionPane.showMessageDialog(this, "La partida ha terminado. Reinicia para jugar de nuevo.");
            return;
        }

        // Si es modo 1 jugador y es turno de la IA, no permitir clics
        if (modoJuego.equals("1_JUGADOR") && partida.getJugadorActual().getColor().equals("NEGRO")) {
            return;
        }

        // Si no hay casilla seleccionada
        if (filaSeleccionada == -1) {
            clsPieza pieza = partida.getTablero().getPieza(fila, columna);

            // Verificar que sea una pieza del jugador actual
            if (pieza != null && pieza.getColor().equals(partida.getJugadorActual().getColor())) {
                filaSeleccionada = fila;
                columnaSeleccionada = columna;

                // Obtener movimientos posibles
                movimientosPosibles = partida.getMovimientosPosibles(fila, columna);

                // Resaltar casilla seleccionada
                botonesTablero[fila][columna].setBackground(COLOR_SELECCIONADA);

                // Resaltar movimientos posibles
                for (int[] mov : movimientosPosibles) {
                    Color colorOriginal = botonesTablero[mov[0]][mov[1]].getBackground();
                    botonesTablero[mov[0]][mov[1]].setBackground(COLOR_MOVIMIENTO_POSIBLE);
                }
            }
        } else {
            // Ya hay una casilla seleccionada, intentar mover
            boolean movimientoRealizado = partida.realizarMovimiento(filaSeleccionada, columnaSeleccionada, fila, columna);

            if (movimientoRealizado) {
                // Verificar si hay promoción de peón
                clsPieza piezaMovida = partida.getTablero().getPieza(fila, columna);
                if (piezaMovida != null && piezaMovida.getTipo().equals("PEON")) {
                    clsPeon peon = (clsPeon) piezaMovida;
                    if (peon.puedePromoverse()) {
                        mostrarDialogoPromocion(fila, columna);
                    }
                }

                // Actualizar interfaz
                actualizarInterfaz();

                // Si es modo 1 jugador, ejecutar turno de la IA
                if (modoJuego.equals("1_JUGADOR") && !partida.isPartidaTerminada()) {
                    ejecutarTurnoIA();
                }
            } else {
                // Movimiento inválido, intentar seleccionar otra pieza
                clsPieza pieza = partida.getTablero().getPieza(fila, columna);
                if (pieza != null && pieza.getColor().equals(partida.getJugadorActual().getColor())) {
                    // Seleccionar nueva pieza
                    actualizarTableroVisual();
                    filaSeleccionada = fila;
                    columnaSeleccionada = columna;
                    movimientosPosibles = partida.getMovimientosPosibles(fila, columna);

                    botonesTablero[fila][columna].setBackground(COLOR_SELECCIONADA);
                    for (int[] mov : movimientosPosibles) {
                        botonesTablero[mov[0]][mov[1]].setBackground(COLOR_MOVIMIENTO_POSIBLE);
                    }
                    return;
                }
            }

            // Limpiar selección
            filaSeleccionada = -1;
            columnaSeleccionada = -1;
            movimientosPosibles = null;
        }
    }

    /**
     * Ejecutar el turno de la IA con un pequeño delay para efecto visual
     */
    private void ejecutarTurnoIA() {
        // Deshabilitar interacción del usuario
        deshabilitarTablero();

        // Usar Timer para dar un pequeño delay (simula "pensamiento")
        Timer timer = new Timer(800, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Realizar movimiento de la IA
                boolean movimientoRealizado = inteligenciaArtificial.realizarMovimiento(partida);

                if (movimientoRealizado) {
                    // Actualizar interfaz
                    actualizarInterfaz();
                }

                // Habilitar interacción del usuario
                habilitarTablero();
            }
        });
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * Deshabilitar todos los botones del tablero
     */
    private void deshabilitarTablero() {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                botonesTablero[i][j].setEnabled(false);
            }
        }
    }

    /**
     * Habilitar todos los botones del tablero
     */
    private void habilitarTablero() {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                botonesTablero[i][j].setEnabled(true);
            }
        }
    }

    /**
     * Mostrar diálogo para promoción de peón
     */
    private void mostrarDialogoPromocion(int fila, int columna) {
        String[] opciones = {"♕ Reina", "♖ Torre", "♗ Alfil", "♘ Caballo"};
        int seleccion = JOptionPane.showOptionDialog(
                this,
                "Selecciona la pieza para promover el peón:",
                "Promoción de Peón",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        String tipoPieza = "REINA"; // Por defecto
        switch (seleccion) {
            case 0:
                tipoPieza = "REINA";
                break;
            case 1:
                tipoPieza = "TORRE";
                break;
            case 2:
                tipoPieza = "ALFIL";
                break;
            case 3:
                tipoPieza = "CABALLO";
                break;
        }

        partida.getTablero().promoverPeon(fila, columna, tipoPieza);
    }

    /**
     * Actualizar todos los elementos de la interfaz
     */
    private void actualizarInterfaz() {
        // Actualizar tablero visual
        actualizarTableroVisual();

        // Actualizar turno y estado
        clsJugador actual = partida.getJugadorActual();
        lblTurno.setText(actual.getNombre() + " (" + actual.getColor() + ")");

        if (actual.isEnJaque()) {
            lblEstado.setText("¡EN JAQUE!");
            lblEstado.setForeground(Color.RED);
        } else {
            lblEstado.setText("");
        }

        // Actualizar piezas capturadas
        actualizarPiezasCapturadas();

        // Actualizar historial de movimientos
        actualizarHistorial();

        // Verificar si la partida terminó
        if (partida.isPartidaTerminada()) {
            String estado = partida.getEstadoPartida();
            JOptionPane.showMessageDialog(this, estado, "Partida Terminada", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * Actualizar las piezas capturadas y puntuaciones
     */
    private void actualizarPiezasCapturadas() {
        // Piezas capturadas por Blancas
        StringBuilder capturadasBlancas = new StringBuilder();
        for (clsPieza pieza : partida.getJugadorBlanco().getPiezasCapturadas()) {
            capturadasBlancas.append(pieza.getSimbolo()).append(" ");
        }
        txtCapturadasBlancas.setText(capturadasBlancas.toString());
        lblPuntuacionBlancas.setText("Puntuación: " + partida.getJugadorBlanco().getPuntuacion());

        // Piezas capturadas por Negras
        StringBuilder capturadasNegras = new StringBuilder();
        for (clsPieza pieza : partida.getJugadorNegro().getPiezasCapturadas()) {
            capturadasNegras.append(pieza.getSimbolo()).append(" ");
        }
        txtCapturadasNegras.setText(capturadasNegras.toString());
        lblPuntuacionNegras.setText("Puntuación: " + partida.getJugadorNegro().getPuntuacion());
    }

    /**
     * Actualizar el historial de movimientos
     */
    private void actualizarHistorial() {
        String notacion = partida.getNotacionAlgebraica();
        txtHistorial.setText(notacion);
        // Desplazar al final
        txtHistorial.setCaretPosition(txtHistorial.getDocument().getLength());
    }

    /**
     * Iniciar nueva partida (evento del botón "Iniciar Juego")
     */
    private void btnIniciarJuegoActionPerformed(ActionEvent evt) {
        iniciarNuevaPartida();
    }

    /**
     * Reiniciar la partida (evento del botón)
     */
    private void btnReiniciarActionPerformed(ActionEvent evt) {
        int confirmar = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas reiniciar la partida?",
                "Confirmar Reinicio",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmar == JOptionPane.YES_OPTION) {
            // Iniciar una nueva partida (mostrará diálogos de modo y dificultad)
            iniciarNuevaPartida();
        }
    }

    /**
     * Deshacer último movimiento (evento del botón)
     */
    private void btnDeshacerActionPerformed(ActionEvent evt) {
        boolean resultado = partida.deshacerMovimiento();
        if (resultado) {
            filaSeleccionada = -1;
            columnaSeleccionada = -1;
            movimientosPosibles = null;
            actualizarInterfaz();
        } else {
            JOptionPane.showMessageDialog(this, "No hay movimientos para deshacer", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Rendirse (evento del botón)
     */
    private void btnRendirseActionPerformed(ActionEvent evt) {
        int confirmar = JOptionPane.showConfirmDialog(
                this,
                partida.getJugadorActual().getNombre() + " ¿Deseas rendirte?",
                "Confirmar Rendición",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmar == JOptionPane.YES_OPTION) {
            String ganador = partida.getJugadorActual().getColor().equals("BLANCO") ? "NEGRO" : "BLANCO";
            JOptionPane.showMessageDialog(
                    this,
                    "Ganan las " + ganador + " por rendición",
                    "Partida Terminada",
                    JOptionPane.INFORMATION_MESSAGE
            );
            partida.reiniciarPartida();
            actualizarInterfaz();
        }
    }
}
