<?php
/**
 * English Language File
 */
$lang = [
    // General
    'app_name' => 'Mercantil Bank',
    'welcome' => 'Welcome',
    'login' => 'Login',
    'logout' => 'Logout',
    'save' => 'Save',
    'cancel' => 'Cancel',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'search' => 'Search',
    'back' => 'Back',
    'actions' => 'Actions',
    'confirm' => 'Confirm',
    'success' => 'Success',
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Information',
    
    // Login
    'username' => 'Username',
    'password' => 'Password',
    'forgot_password' => 'Forgot your password?',
    'login_error' => 'Incorrect username or password',
    
    // Dashboard
    'dashboard' => 'Dashboard',
    'clients' => 'Clients',
    'accounts' => 'Accounts',
    'transactions' => 'Transactions',
    'reports' => 'Reports',
    'branches' => 'Branches',
    'total_clients' => 'Total clients',
    'total_accounts' => 'Total accounts',
    'today_transactions' => 'Today\'s transactions',
    'recent_transactions' => 'Recent Transactions',
    
    // Clients
    'new_client' => 'New Client',
    'client_list' => 'Client List',
    'name' => 'Name',
    'last_name' => 'Last Name',
    'maternal_last_name' => 'Maternal Last Name',
    'paternal_last_name' => 'Paternal Last Name',
    'id_number' => 'ID Number',
    'address' => 'Address',
    'phone' => 'Phone',
    'email' => 'Email',
    'birth_date' => 'Birth Date',
    'client_details' => 'Client Details',
    'client_saved' => 'Client saved successfully',
    'client_updated' => 'Client updated successfully',
    'client_deleted' => 'Client deleted successfully',
    
    // Accounts
    'new_account' => 'New Account',
    'account_list' => 'Account List',
    'account_number' => 'Account Number',
    'account_type' => 'Account Type',
    'savings_account' => 'Savings Account',
    'checking_account' => 'Checking Account',
    'currency' => 'Currency',
    'bolivianos' => 'Bolivianos',
    'dollars' => 'Dollars',
    'balance' => 'Balance',
    'opening_date' => 'Opening Date',
    'status' => 'Status',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'account_details' => 'Account Details',
    'account_saved' => 'Account saved successfully',
    'account_updated' => 'Account updated successfully',
    'account_deleted' => 'Account deleted successfully',
    'select_client' => 'Select Client',
    
    // Transactions
    'new_transaction' => 'New Transaction',
    'transaction_list' => 'Transaction List',
    'transaction_id' => 'Transaction ID',
    'transaction_type' => 'Transaction Type',
    'deposit' => 'Deposit',
    'withdrawal' => 'Withdrawal',
    'amount' => 'Amount',
    'date' => 'Date',
    'time' => 'Time',
    'description' => 'Description',
    'transaction_details' => 'Transaction Details',
    'transaction_saved' => 'Transaction completed successfully',
    'insufficient_funds' => 'Insufficient funds to complete this operation',
    'select_account' => 'Select Account',
    'transaction_history' => 'Transaction History',
    'start_date' => 'Start Date',
    'end_date' => 'End Date',
    'generate_report' => 'Generate Report',
    'print' => 'Print',
    
    // Offices
    'new_office' => 'New Office',
    'office_list' => 'Office List',
    'office_id' => 'Office ID',
    'office_name' => 'Office Name',
    'central_office' => 'Central Office',
    'branch_office' => 'Branch Office',
    'office_details' => 'Office Details',
    'office_saved' => 'Office saved successfully',
    'office_updated' => 'Office updated successfully',
    'office_deleted' => 'Office deleted successfully',
    
    // ATM
    'atm' => 'ATM',
    'atm_id' => 'ATM ID',
    'location' => 'Location',
    'atm_transaction' => 'ATM Transaction',
    
    // Cards
    'cards' => 'Cards',
    'card_number' => 'Card Number',
    'expiration_date' => 'Expiration Date',
    'cvv' => 'CVV',
    'pin' => 'PIN',
    
    // Errors
    'page_not_found' => 'Page not found',
    'access_denied' => 'Access denied',
    'session_expired' => 'Your session has expired, please login again',
    'system_error' => 'System error, please try again later',
    
    // Reports
    'reports' => 'Reports',
    'transactions_by_date' => 'Transactions by Date',
    'transactions_by_date_desc' => 'Report of all transactions made within a specific date range.',
    'transactions_by_client' => 'Transactions by Client',
    'transactions_by_client_desc' => 'Report of all transactions made by a specific client.',
    'atm_statistics' => 'ATM Statistics',
    'atm_statistics_desc' => 'Statistics report on ATM usage.',
    'balances_by_branch' => 'Balances by Branch',
    'balances_by_branch_desc' => 'Report of total balances managed by each branch office.',
    'search_criteria' => 'Search Criteria',
    'select_client' => 'Select Client',
    'select_atm' => 'Select ATM',
    'select_option' => 'Select an option',
    'generate_report' => 'Generate Report',
    'view_report' => 'View Report',
    'results' => 'Results',
    'print' => 'Print',
    'close' => 'Close',
    'period' => 'Period',
    'total_transactions' => 'Total Transactions',
    'total_deposits' => 'Total Deposits',
    'total_withdrawals' => 'Total Withdrawals',
    'no_transactions_found' => 'No transactions found for the selected criteria.',
    'withdrawals' => 'Withdrawals',
    'deposits' => 'Deposits',
    'withdrawal_amount' => 'Withdrawal Amount',
    'deposit_amount' => 'Deposit Amount',
    'totals' => 'Totals',
    'clients_and_accounts_by_branch' => 'Clients and Accounts by Branch',
    'view' => 'View',
    'no_transactions' => 'No recent transactions.'
];
?>