<?php
/**
 * Spanish Language File
 */
$lang = [
    // General
    'app_name' => 'Banco Mercantil',
    'welcome' => 'Bienvenido',
    'login' => 'Iniciar Sesión',
    'logout' => 'Cerrar Sesión',
    'save' => 'Guardar',
    'cancel' => 'Cancelar',
    'edit' => 'Editar',
    'delete' => 'Eliminar',
    'search' => 'Buscar',
    'back' => 'Volver',
    'actions' => 'Acciones',
    'confirm' => 'Confirmar',
    'success' => 'Éxito',
    'error' => 'Error',
    'warning' => 'Advertencia',
    'info' => 'Información',
    
    // Login
    'username' => 'Usuario',
    'password' => 'Contraseña',
    'forgot_password' => '¿Olvidaste tu contraseña?',
    'login_error' => 'Usuario o contraseña incorrectos',
    
    // Dashboard
    'dashboard' => 'Dashboard',
    'clients' => 'Clientes',
    'accounts' => 'Cuentas',
    'transactions' => 'Transacciones',
    'reports' => 'Reportes',
    'branches' => 'Oficinas',
    'total_clients' => 'Total de clientes',
    'total_accounts' => 'Total de cuentas',
    'today_transactions' => 'Transacciones hoy',
    'recent_transactions' => 'Transacciones Recientes',
    
    // Clients
    'new_client' => 'Nuevo Cliente',
    'client_list' => 'Lista de Clientes',
    'name' => 'Nombre',
    'last_name' => 'Apellido',
    'maternal_last_name' => 'Apellido Materno',
    'paternal_last_name' => 'Apellido Paterno',
    'id_number' => 'Cédula de Identidad',
    'address' => 'Dirección',
    'phone' => 'Teléfono',
    'email' => 'Correo Electrónico',
    'birth_date' => 'Fecha de Nacimiento',
    'client_details' => 'Detalles del Cliente',
    'client_saved' => 'Cliente guardado exitosamente',
    'client_updated' => 'Cliente actualizado exitosamente',
    'client_deleted' => 'Cliente eliminado exitosamente',
    
    // Accounts
    'new_account' => 'Nueva Cuenta',
    'account_list' => 'Lista de Cuentas',
    'account_number' => 'Número de Cuenta',
    'account_type' => 'Tipo de Cuenta',
    'savings_account' => 'Cuenta de Ahorro',
    'checking_account' => 'Cuenta Corriente',
    'currency' => 'Moneda',
    'bolivianos' => 'Bolivianos',
    'dollars' => 'Dólares',
    'balance' => 'Saldo',
    'opening_date' => 'Fecha de Apertura',
    'status' => 'Estado',
    'active' => 'Activa',
    'inactive' => 'Inactiva',
    'account_details' => 'Detalles de la Cuenta',
    'account_saved' => 'Cuenta guardada exitosamente',
    'account_updated' => 'Cuenta actualizada exitosamente',
    'account_deleted' => 'Cuenta eliminada exitosamente',
    'select_client' => 'Seleccionar Cliente',
    
    // Transactions
    'new_transaction' => 'Nueva Transacción',
    'transaction_list' => 'Lista de Transacciones',
    'transaction_id' => 'ID Transacción',
    'transaction_type' => 'Tipo de Transacción',
    'deposit' => 'Depósito',
    'withdrawal' => 'Retiro',
    'amount' => 'Monto',
    'date' => 'Fecha',
    'time' => 'Hora',
    'description' => 'Descripción',
    'transaction_details' => 'Detalles de la Transacción',
    'transaction_saved' => 'Transacción realizada exitosamente',
    'insufficient_funds' => 'Fondos insuficientes para realizar esta operación',
    'select_account' => 'Seleccionar Cuenta',
    'transaction_history' => 'Historial de Transacciones',
    'start_date' => 'Fecha Inicial',
    'end_date' => 'Fecha Final',
    'generate_report' => 'Generar Reporte',
    'print' => 'Imprimir',
    
    // Offices
    'new_office' => 'Nueva Oficina',
    'office_list' => 'Lista de Oficinas',
    'office_id' => 'ID Oficina',
    'office_name' => 'Nombre de Oficina',
    'central_office' => 'Oficina Central',
    'branch_office' => 'Agencia',
    'office_details' => 'Detalles de la Oficina',
    'office_saved' => 'Oficina guardada exitosamente',
    'office_updated' => 'Oficina actualizada exitosamente',
    'office_deleted' => 'Oficina eliminada exitosamente',
    
    // ATM
    'atm' => 'Cajero Automático',
    'atm_id' => 'ID Cajero',
    'location' => 'Ubicación',
    'atm_transaction' => 'Transacción en Cajero',
    
    // Cards
    'cards' => 'Tarjetas',
    'card_number' => 'Número de Tarjeta',
    'expiration_date' => 'Fecha de Expiración',
    'cvv' => 'CVV',
    'pin' => 'PIN',
    
    // Errors
    'page_not_found' => 'Página no encontrada',
    'access_denied' => 'Acceso denegado',
    'session_expired' => 'Su sesión ha expirado, por favor inicie sesión nuevamente',
    'system_error' => 'Error en el sistema, por favor intente nuevamente más tarde',
    
    // Reportes
    'reports' => 'Reportes',
    'transactions_by_date' => 'Transacciones por Fecha',
    'transactions_by_date_desc' => 'Reporte de todas las transacciones realizadas en un rango de fechas específico.',
    'transactions_by_client' => 'Transacciones por Cliente',
    'transactions_by_client_desc' => 'Reporte de todas las transacciones realizadas por un cliente específico.',
    'atm_statistics' => 'Estadísticas de ATM',
    'atm_statistics_desc' => 'Reporte de estadísticas de uso de cajeros automáticos.',
    'balances_by_branch' => 'Saldos por Oficina',
    'balances_by_branch_desc' => 'Reporte de saldos totales administrados por cada oficina.',
    'search_criteria' => 'Criterios de Búsqueda',
    'select_client' => 'Seleccionar Cliente',
    'select_atm' => 'Seleccionar ATM',
    'select_option' => 'Seleccione una opción',
    'generate_report' => 'Generar Reporte',
    'view_report' => 'Ver Reporte',
    'results' => 'Resultados',
    'print' => 'Imprimir',
    'close' => 'Cerrar',
    'period' => 'Período',
    'total_transactions' => 'Total de Transacciones',
    'total_deposits' => 'Total de Depósitos',
    'total_withdrawals' => 'Total de Retiros',
    'no_transactions_found' => 'No se encontraron transacciones para los criterios seleccionados.',
    'withdrawals' => 'Retiros',
    'deposits' => 'Depósitos',
    'withdrawal_amount' => 'Monto de Retiros',
    'deposit_amount' => 'Monto de Depósitos',
    'totals' => 'Totales',
    'clients_and_accounts_by_branch' => 'Clientes y Cuentas por Oficina',
    'view' => 'Ver',
    'no_transactions' => 'No hay transacciones recientes.'
];
?>